# Data Cleaning / Pre-processing

In [3]:
# Getting raw data from Google Drive
!pip install gdown
import gdown
!gdown "https://drive.google.com/uc?id=1n1GjVm7XwtC1Yd-25n5IE8gGVXuKmTVZ&export=download"

Collecting gdown
  Using cached gdown-4.2.0.tar.gz (13 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: tqdm in c:\users\kazis\anaconda3\lib\site-packages (from gdown) (4.62.3)
Requirement already satisfied: six in c:\users\kazis\anaconda3\lib\site-packages (from gdown) (1.15.0)
Requirement already satisfied: beautifulsoup4 in c:\users\kazis\anaconda3\lib\site-packages (from gdown) (4.10.0)
Requirement already satisfied: filelock in c:\users\kazis\anaconda3\lib\site-packages (from gdown) (3.4.0)
Requirement already satisfied: requests[socks] in c:\users\kazis\anaconda3\lib\site-packages (from gdown) (2.26.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\kazis\anaconda3\lib\site-packages (from beautifulsoup4->gdown) (2.3.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kazis\anaconda3\lib\site-packages (from requests[socks]->gdown) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kazis\anaconda3\lib\site-packages (from requests[socks]->gdown) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\kazis\anaconda3\lib\site-packages (from requests[socks]->gdown) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\kazis\anaconda3\lib\site-packages (from requests[socks]->gdown) (2.0.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\kazis\anaconda3\lib\site-packages (from requests[socks]->gdown) (1.7.1)
Requirement already satisfied: colorama in c:\users\kazis\anaconda3\lib\site-packages (from tqdm->gdown) (0.4.4)
Building wheels for collected packages: gdown
  Building wheel for gdown (PEP 517): started
  Building wheel for gdown (PEP 517): finished with status 'done'
  Created wheel for gdown: filename=gdown-4.2.0-py3-none-any.whl size=14262 sha256=b622e34c513851a33935a04784fe4a24736b72732badf662b6628d62f2417bba
  Stored in directory: c:\users\kazis\appdata\local\pip\cache\wheels\2b\3c\51\52c46deda5cd1d59c6ce3d441ea5f3d155495dc294c4535a25
Successfully built gdown
Installing collected packages: gdown
Successfully installed gdown-4.2.0

Downloading...
From: https://drive.google.com/uc?id=1n1GjVm7XwtC1Yd-25n5IE8gGVXuKmTVZ&export=download
To: C:\Users\kazis\OneDrive\Desktop\Data Science Projects\Final Data Science Project\data-science-final-project\Preliminary Analysis\Jupyter Notebook Files\Motor_Vehicle_Collisions_-_Crashes.csv

  0%|          | 0.00/396M [00:00<?, ?B/s]
  0%|          | 1.05M/396M [00:00<00:38, 10.3MB/s]
  1%|          | 2.62M/396M [00:00<00:29, 13.1MB/s]
  1%|1         | 4.19M/396M [00:00<00:34, 11.4MB/s]
  1%|1         | 5.77M/396M [00:00<00:33, 11.7MB/s]
  2%|1         | 7.34M/396M [00:00<00:34, 11.3MB/s]
  2%|2         | 9.44M/396M [00:00<00:29, 13.0MB/s]
  3%|2         | 11.0M/396M [00:00<00:29, 13.1MB/s]
  3%|3         | 13.1M/396M [00:01<00:26, 14.6MB/s]
  4%|3         | 15.2M/396M [00:01<00:25, 15.1MB/s]
  4%|4         | 17.3M/396M [00:01<00:24, 15.6MB/s]
  5%|4         | 19.4M/396M [00:01<00:24, 15.6MB/s]
  5%|5         | 21.5M/396M [00:01<00:22, 16.4MB/s]
  6%|5         | 23.6M/396M [00:01<00:22, 16.3MB/s]
  6%|6         | 25.7M/396M [00:01<00:22, 16.3MB/s]
  7%|7         | 27.8M/396M [00:01<00:22, 16.2MB/s]
  8%|7         | 29.9M/396M [00:01<00:21, 17.2MB/s]
  8%|8         | 32.0M/396M [00:02<00:23, 15.6MB/s]
  9%|8         | 34.6M/396M [00:02<00:21, 16.5MB/s]
  9%|9         | 36.7M/396M [00:02<00:20, 17.5MB/s]
 10%|9         | 39.3M/396M [00:02<00:18, 19.1MB/s]
 11%|#         | 41.9M/396M [00:02<00:17, 20.1MB/s]
 11%|#1        | 45.1M/396M [00:02<00:16, 21.8MB/s]
 12%|#2        | 47.7M/396M [00:02<00:16, 21.3MB/s]
 13%|#2        | 50.3M/396M [00:02<00:15, 22.4MB/s]
 13%|#3        | 53.0M/396M [00:03<00:16, 21.3MB/s]
 14%|#4        | 55.6M/396M [00:03<00:16, 20.5MB/s]
 15%|#4        | 58.2M/396M [00:03<00:15, 21.2MB/s]
 15%|#5        | 60.8M/396M [00:03<00:15, 22.0MB/s]
 16%|#6        | 63.4M/396M [00:03<00:15, 21.5MB/s]
 17%|#6        | 66.1M/396M [00:03<00:15, 21.3MB/s]
 17%|#7        | 68.7M/396M [00:03<00:14, 21.8MB/s]
 18%|#8        | 71.3M/396M [00:03<00:14, 22.3MB/s]
 19%|#8        | 73.9M/396M [00:04<00:14, 22.5MB/s]
 19%|#9        | 76.5M/396M [00:04<00:16, 19.1MB/s]
 20%|##        | 79.2M/396M [00:04<00:15, 20.5MB/s]
 21%|##        | 81.8M/396M [00:04<00:14, 21.5MB/s]
 21%|##1       | 84.4M/396M [00:04<00:14, 21.3MB/s]
 22%|##1       | 87.0M/396M [00:04<00:15, 20.5MB/s]
 23%|##2       | 89.1M/396M [00:04<00:15, 20.0MB/s]
 23%|##3       | 91.2M/396M [00:04<00:16, 19.0MB/s]
 24%|##3       | 93.3M/396M [00:05<00:20, 15.0MB/s]
 24%|##4       | 95.4M/396M [00:05<00:19, 15.5MB/s]
 25%|##4       | 97.5M/396M [00:05<00:18, 16.6MB/s]
 25%|##5       | 99.6M/396M [00:05<00:17, 16.8MB/s]
 26%|##5       | 102M/396M [00:05<00:16, 17.4MB/s]
 26%|##6       | 104M/396M [00:05<00:15, 19.2MB/s]
 27%|##7       | 107M/396M [00:05<00:14, 19.9MB/s]
 28%|##7       | 109M/396M [00:06<00:14, 19.6MB/s]
 28%|##8       | 112M/396M [00:06<00:13, 20.5MB/s]
 29%|##8       | 114M/396M [00:06<00:13, 20.4MB/s]
 29%|##9       | 116M/396M [00:06<00:14, 19.7MB/s]
 30%|##9       | 118M/396M [00:06<00:13, 20.0MB/s]
 31%|###       | 121M/396M [00:06<00:13, 20.8MB/s]
 31%|###1      | 123M/396M [00:06<00:13, 20.5MB/s]
 32%|###1      | 126M/396M [00:06<00:12, 21.1MB/s]
 32%|###2      | 128M/396M [00:06<00:12, 21.7MB/s]
 33%|###3      | 131M/396M [00:07<00:11, 22.2MB/s]
 34%|###3      | 134M/396M [00:07<00:11, 22.3MB/s]
 34%|###4      | 136M/396M [00:07<00:11, 22.6MB/s]
 35%|###5      | 139M/396M [00:07<00:11, 22.6MB/s]
 36%|###5      | 142M/396M [00:07<00:11, 22.0MB/s]
 36%|###6      | 144M/396M [00:07<00:10, 22.9MB/s]
 37%|###7      | 147M/396M [00:07<00:10, 23.1MB/s]
 38%|###7      | 150M/396M [00:07<00:10, 23.6MB/s]
 39%|###8      | 153M/396M [00:07<00:11, 21.7MB/s]
 39%|###9      | 155M/396M [00:08<00:11, 20.8MB/s]
 40%|###9      | 158M/396M [00:08<00:12, 19.3MB/s]
 40%|####      | 160M/396M [00:08<00:13, 17.8MB/s]
 41%|####      | 162M/396M [00:08<00:12, 18.5MB/s]
 42%|####1     | 165M/396M [00:08<00:11, 19.3MB/s]
 42%|####2     | 167M/396M [00:08<00:11, 19.4MB/s]
 43%|####2     | 169M/396M [00:08<00:11, 19.0MB/s]
 43%|####3     | 172M/396M [00:09<00:10, 20.4MB/s]
 44%|####4     | 175M/396M [00:09<00:10, 21.1MB/s]
 45%|####4     | 177M/396M [00:09<00:10, 21.1MB/s]
 45%|####5     | 180M/396M [00:09<00:10, 21.5MB/s]
 46%|####6     | 182M/396M [00:09<00:09, 22.0MB/s]
 47%|####6     | 185M/396M [00:09<00:09, 21.8MB/s]
 48%|####7     | 188M/396M [00:09<00:09, 22.2MB/s]
 48%|####8     | 191M/396M [00:09<00:08, 23.3MB/s]
 49%|####9     | 194M/396M [00:09<00:08, 23.3MB/s]
 50%|####9     | 197M/396M [00:10<00:08, 22.9MB/s]
 50%|#####     | 199M/396M [00:10<00:08, 23.5MB/s]
 51%|#####1    | 202M/396M [00:10<00:09, 20.8MB/s]
 52%|#####1    | 204M/396M [00:10<00:11, 16.2MB/s]
 52%|#####2    | 207M/396M [00:10<00:11, 17.1MB/s]
 53%|#####2    | 209M/396M [00:10<00:11, 16.9MB/s]
 53%|#####3    | 211M/396M [00:10<00:10, 17.3MB/s]
 54%|#####3    | 213M/396M [00:11<00:10, 17.2MB/s]
 54%|#####4    | 215M/396M [00:11<00:10, 16.7MB/s]
 55%|#####4    | 218M/396M [00:11<00:10, 16.9MB/s]
 56%|#####5    | 220M/396M [00:11<00:09, 18.5MB/s]
 56%|#####6    | 223M/396M [00:11<00:08, 19.7MB/s]
 57%|#####6    | 225M/396M [00:11<00:08, 21.1MB/s]
 58%|#####7    | 228M/396M [00:11<00:07, 21.6MB/s]
 58%|#####8    | 231M/396M [00:11<00:07, 22.4MB/s]
 59%|#####8    | 233M/396M [00:12<00:07, 22.2MB/s]
 60%|#####9    | 236M/396M [00:12<00:07, 22.2MB/s]
 60%|######    | 239M/396M [00:12<00:07, 22.2MB/s]
 61%|######    | 241M/396M [00:12<00:06, 22.2MB/s]
 62%|######1   | 244M/396M [00:12<00:06, 22.0MB/s]
 62%|######2   | 246M/396M [00:12<00:07, 21.0MB/s]
 63%|######3   | 250M/396M [00:12<00:06, 21.9MB/s]
 64%|######3   | 252M/396M [00:12<00:06, 22.5MB/s]
 64%|######4   | 255M/396M [00:13<00:06, 21.9MB/s]
 65%|######5   | 257M/396M [00:13<00:06, 21.8MB/s]
 66%|######5   | 260M/396M [00:13<00:06, 21.8MB/s]
 66%|######6   | 263M/396M [00:13<00:06, 21.9MB/s]
 67%|######7   | 265M/396M [00:13<00:06, 19.9MB/s]
 68%|######7   | 268M/396M [00:13<00:07, 17.9MB/s]
 68%|######8   | 270M/396M [00:13<00:07, 17.1MB/s]
 69%|######8   | 272M/396M [00:14<00:08, 15.2MB/s]
 69%|######9   | 274M/396M [00:14<00:08, 14.9MB/s]
 70%|######9   | 276M/396M [00:14<00:07, 15.7MB/s]
 70%|#######   | 278M/396M [00:14<00:07, 15.8MB/s]
 71%|#######   | 280M/396M [00:14<00:07, 15.1MB/s]
 72%|#######1  | 283M/396M [00:14<00:06, 17.0MB/s]
 72%|#######2  | 286M/396M [00:14<00:06, 17.8MB/s]
 73%|#######2  | 288M/396M [00:15<00:10, 9.86MB/s]
 73%|#######3  | 289M/396M [00:15<00:11, 9.30MB/s]
 74%|#######3  | 291M/396M [00:15<00:11, 9.15MB/s]
 74%|#######3  | 293M/396M [00:15<00:11, 9.32MB/s]
 74%|#######4  | 294M/396M [00:16<00:10, 9.56MB/s]
 75%|#######4  | 296M/396M [00:16<00:09, 10.2MB/s]
 75%|#######5  | 297M/396M [00:16<00:08, 11.1MB/s]
 76%|#######5  | 299M/396M [00:16<00:08, 11.7MB/s]
 76%|#######6  | 301M/396M [00:16<00:07, 13.4MB/s]
 77%|#######6  | 303M/396M [00:16<00:06, 14.8MB/s]
 77%|#######7  | 305M/396M [00:16<00:05, 16.2MB/s]
 78%|#######7  | 308M/396M [00:16<00:04, 17.9MB/s]
 78%|#######8  | 310M/396M [00:16<00:04, 17.8MB/s]
 79%|#######8  | 312M/396M [00:17<00:04, 16.9MB/s]
 79%|#######9  | 314M/396M [00:17<00:05, 16.3MB/s]
 80%|#######9  | 316M/396M [00:17<00:04, 16.5MB/s]
 80%|########  | 318M/396M [00:17<00:04, 17.3MB/s]
 81%|########1 | 321M/396M [00:17<00:04, 17.9MB/s]
 82%|########1 | 323M/396M [00:17<00:03, 18.4MB/s]
 82%|########2 | 326M/396M [00:17<00:03, 20.5MB/s]
 83%|########3 | 329M/396M [00:17<00:03, 21.3MB/s]
 84%|########3 | 331M/396M [00:18<00:02, 22.0MB/s]
 84%|########4 | 334M/396M [00:18<00:02, 23.1MB/s]
 85%|########5 | 337M/396M [00:18<00:02, 23.2MB/s]
 86%|########5 | 339M/396M [00:18<00:02, 22.7MB/s]
 86%|########6 | 342M/396M [00:18<00:02, 22.3MB/s]
 87%|########7 | 345M/396M [00:18<00:02, 23.7MB/s]
 88%|########7 | 348M/396M [00:18<00:02, 23.4MB/s]
 89%|########8 | 350M/396M [00:18<00:01, 23.9MB/s]
 89%|########9 | 353M/396M [00:18<00:02, 21.4MB/s]
 90%|########9 | 356M/396M [00:19<00:01, 23.9MB/s]
 91%|######### | 359M/396M [00:19<00:01, 23.8MB/s]
 91%|#########1| 361M/396M [00:19<00:01, 23.1MB/s]
 92%|#########1| 364M/396M [00:19<00:01, 23.7MB/s]
 93%|#########2| 366M/396M [00:19<00:01, 23.7MB/s]
 93%|#########3| 369M/396M [00:19<00:01, 24.0MB/s]
 94%|#########3| 372M/396M [00:19<00:01, 22.9MB/s]
 95%|#########4| 375M/396M [00:19<00:00, 23.5MB/s]
 95%|#########5| 377M/396M [00:19<00:00, 23.2MB/s]
 96%|#########6| 380M/396M [00:20<00:00, 22.4MB/s]
 97%|#########6| 383M/396M [00:20<00:00, 22.2MB/s]
 97%|#########7| 385M/396M [00:20<00:00, 22.1MB/s]
 98%|#########8| 388M/396M [00:20<00:00, 22.0MB/s]
 99%|#########8| 391M/396M [00:20<00:00, 18.8MB/s]
 99%|#########9| 393M/396M [00:20<00:00, 17.3MB/s]
100%|#########9| 395M/396M [00:20<00:00, 18.5MB/s]
100%|##########| 396M/396M [00:20<00:00, 18.9MB/s]

In [5]:
# Import library
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

# About Data

- The data we're going to use can be accessed here: https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Crashes/h9gi-nx95 
- It is about Motor Vehicle Collisions crash. Each row represents a crash event. The Motor Vehicle Collisions data contains information from all police reported motor vehicle collisions in NYC. It has about 600,000 rows and 29 columns.

# Data Dictionary

- CRASH DATE: Occurrence date of collision. Datatype: String.
- CRASH TIME: Occurrence time of collision. Datatype: String.
- BOROUGH:  Borough where collision occurred. Datatype: String.
- ZIP CODE:  Postal code of incident occurrence. Datatype: String.
- LATITUDE: Latitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326). Datatype: Float64. 
- LONGITUDE: Longitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326). Datatype: Float64. 
- LOCATION: Latitude, Longitude pair. Datatype: String.
- ON STREET NAME: Street on which the collision occurred. Datatype: String.
- CROSS STREET NAME: Nearest cross street to the collision. Datatype: String.
- OFF STREET NAME: Street address if known. Datatype: String.
- NUMBER OF PERSONS INJURED: Number of persons injured. Datatype: Float64.
- NUMBER OF PERSONS KILLED: Number of persons killed. Datatype: Float64. 
- NUMBER OF PEDESTRIANS INJURED: Number of pedestrians injured. Datatype: Int64.
- NUMBER OF PEDESTRIANS KILLED: Number of pedestrians killed. Datatype: Int64.
- NUMBER OF CYCLIST INJURED: Number of cyclists injured. Datatype: Int64.
- NUMBER OF CYCLIST KILLED: Number of cyclists killed. Datatype: Int64.
- NUMBER OF MOTORIST INJURED: Number of vehicle occupants injured. Datatype: Int64.
- NUMBER OF MOTORIST KILLED: Number of vehicle occupants killed. Datatype: Int64.
- CONTRIBUTING FACTOR VEHICLE 1: Factors contributing to the collision for designated vehicle. Datatype: String.
- CONTRIBUTING FACTOR VEHICLE 2: Factors contributing to the collision for designated vehicle. Datatype: String.
- CONTRIBUTING FACTOR VEHICLE 3: Factors contributing to the collision for designated vehicle. Datatype: String.
- CONTRIBUTING FACTOR VEHICLE 4: Factors contributing to the collision for designated vehicle. Datatype: String.
- CONTRIBUTING FACTOR VEHICLE 5: Factors contributing to the collision for designated vehicle. Datatype: String.
- COLLISION_ID: Unique record code generated by system. Primary Key for Crash table. Datatype: Int64.
- VEHICLE TYPE CODE 1: Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other). Datatype: String.
- VEHICLE TYPE CODE 2: Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other). Datatype: String.
- VEHICLE TYPE CODE 3: Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other). Datatype: String.
- VEHICLE TYPE CODE 4: Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other). Datatype: String.
- VEHICLE TYPE CODE 5: Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other). Datatype: String.

# Data Cleaning / Processing

- As the dataset is huge, we're going to take 50,000 random samples from it to ease our process and to make it efficient for this task.
- Also, there are a number of features that we actually don't need for our problem. Hence, we have to drop those features since they will be having no effect on our output. 
- Finally, comes the part of dealing with the missing values. Since some of the features contain alot of missing values (including our target feature), we will have to fix them. Starting from our target feature, since it is a categorical feature and our dataset is huge, so we're simply going to drop missing values in our target variable.
- After that, we're going to compute missing values for the test of our features. Since our data contains no outliers at all, we will fill all the missing values using the mean strategy.
- After that, we will fix the datatype of each column.

In [6]:
#importing our dataset
df = pd.read_csv("./Motor_Vehicle_Collisions_-_Crashes.csv")

In [3]:
df.head()

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,04/14/2021,5:32,NaN,NaN,NaN,NaN,NaN,BRONX WHITESTONE BRIDGE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4407480,Sedan,Sedan,NaN,NaN,NaN
1,04/13/2021,21:35,BROOKLYN,11217.0,40.68358,-73.97617,"(40.68358, -73.97617)",NaN,NaN,620 ATLANTIC AVENUE,...,NaN,NaN,NaN,NaN,4407147,Sedan,NaN,NaN,NaN,NaN
2,04/15/2021,16:15,NaN,NaN,NaN,NaN,NaN,HUTCHINSON RIVER PARKWAY,NaN,NaN,...,NaN,NaN,NaN,NaN,4407665,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
3,04/13/2021,16:00,BROOKLYN,11222.0,NaN,NaN,NaN,VANDERVORT AVENUE,ANTHONY STREET,NaN,...,Unspecified,NaN,NaN,NaN,4407811,Sedan,NaN,NaN,NaN,NaN
4,04/12/2021,8:25,NaN,NaN,0.00000,0.00000,"(0.0, 0.0)",EDSON AVENUE,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4406885,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN

In [4]:
df.shape

(1838945, 29)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1838945 entries, 0 to 1838944
Data columns (total 29 columns):
 #   Column                         Dtype
---  ------                         -----
 0   CRASH DATE                     object
 1   CRASH TIME                     object
 2   BOROUGH                        object
 3   ZIP CODE                       object
 4   LATITUDE                       float64
 5   LONGITUDE                      float64
 6   LOCATION                       object
 7   ON STREET NAME                 object
 8   CROSS STREET NAME              object
 9   OFF STREET NAME                object
 10  NUMBER OF PERSONS INJURED      float64
 11  NUMBER OF PERSONS KILLED       float64
 12  NUMBER OF PEDESTRIANS INJURED  int64
 13  NUMBER OF PEDESTRIANS KILLED   int64
 14  NUMBER OF CYCLIST INJURED      int64
 15  NUMBER OF CYCLIST KILLED       int64
 16  NUMBER OF MOTORIST INJURED     int64
 17  NUMBER OF MOTORIST KILLED      int64
 18  CONTRIBUTING FACTOR VEHICLE 1  object
 19  CONTRIBUTING FACTOR VEHICLE 2  object
 20  CONTRIBUTING FACTOR VEHICLE 3  object
 21  CONTRIBUTING FACTOR VEHICLE 4  object
 22  CONTRIBUTING FACTOR VEHICLE 5  object
 23  COLLISION_ID                   int64
 24  VEHICLE TYPE CODE 1            object
 25  VEHICLE TYPE CODE 2            object
 26  VEHICLE TYPE CODE 3            object
 27  VEHICLE TYPE CODE 4            object
 28  VEHICLE TYPE CODE 5            object
dtypes: float64(4), int64(7), object(18)
memory usage: 406.9+ MB

In [6]:
#Taking 50,000 random samples from our data.
df = df.sample(n=50000)

In [7]:
#Checking the shape of our data
df.shape

(50000, 29)

In [8]:
#Statistical summary of our data
df.describe()

,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,COLLISION_ID
count,44191.000000,44191.000000,49999.000000,49999.000000,50000.000000,50000.000000,50000.000000,50000.0000,50000.000000,50000.000000,5.000000e+04
mean,40.676364,-73.842396,0.278046,0.001180,0.053000,0.000600,0.023820,0.0001,0.200200,0.000500,2.972658e+06
std,1.384910,2.731782,0.670008,0.035478,0.235015,0.025291,0.154962,0.0100,0.632177,0.023233,1.501561e+06
min,0.000000,-201.237060,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,1.420000e+02
25%,40.667461,-73.975808,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,2.966000e+06
50%,40.720979,-73.928611,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,3.549654e+06
75%,40.768795,-73.866630,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,4.011352e+06
max,41.347960,0.000000,18.000000,2.000000,4.000000,2.000000,2.000000,1.0000,18.000000,2.000000,4.475499e+06

In [9]:
#Checking for missing values
df.isnull().sum()

CRASH DATE                           0
CRASH TIME                           0
BOROUGH                          15218
ZIP CODE                         15220
LATITUDE                          5809
LONGITUDE                         5809
LOCATION                          5809
ON STREET NAME                   10200
CROSS STREET NAME                17831
OFF STREET NAME                  42303
NUMBER OF PERSONS INJURED            1
NUMBER OF PERSONS KILLED             1
NUMBER OF PEDESTRIANS INJURED        0
NUMBER OF PEDESTRIANS KILLED         0
NUMBER OF CYCLIST INJURED            0
NUMBER OF CYCLIST KILLED             0
NUMBER OF MOTORIST INJURED           0
NUMBER OF MOTORIST KILLED            0
CONTRIBUTING FACTOR VEHICLE 1      153
CONTRIBUTING FACTOR VEHICLE 2     7195
CONTRIBUTING FACTOR VEHICLE 3    46599
CONTRIBUTING FACTOR VEHICLE 4    49292
CONTRIBUTING FACTOR VEHICLE 5    49823
COLLISION_ID                         0
VEHICLE TYPE CODE 1                286
VEHICLE TYPE CODE 2               8553
VEHICLE TYPE CODE 3              46712
VEHICLE TYPE CODE 4              49313
VEHICLE TYPE CODE 5              49827
dtype: int64

In [10]:
#Keeping only the required features
columns = ["CRASH DATE", "CRASH TIME", "BOROUGH", "LATITUDE", "LONGITUDE", "NUMBER OF PERSONS INJURED",\
          "NUMBER OF PERSONS KILLED","NUMBER OF PEDESTRIANS INJURED", "NUMBER OF PEDESTRIANS KILLED",\
          "NUMBER OF CYCLIST INJURED", "NUMBER OF CYCLIST KILLED", "NUMBER OF MOTORIST INJURED",\
          "NUMBER OF MOTORIST KILLED"]

In [11]:
#Keeping only the required features in our dataset
df = df[columns]

In [12]:
df.dropna(subset=["BOROUGH"], inplace=True)
df.shape

(34782, 13)

In [13]:
#Checking for outliers
print("Mean of Latitude: ", df["LATITUDE"].mean())
print("Median of Latitude: ", df["LATITUDE"].median())
print("\nSince both the values are approx. same, it means there are no outliers in latitude & longitude.")

Mean of Latitude:  40.67402280233771
Median of Latitude:  40.71886135

Since both the values are approx. same, it means there are no outliers in latitude & longitude.

In [14]:
#Filling missing values
df["LATITUDE"].fillna(df["LATITUDE"].mean(), inplace=True)
df["LONGITUDE"].fillna(df["LONGITUDE"].mean(), inplace=True)
df.dropna(inplace=True)

In [15]:
#Checking again for missing values
df.isnull().sum()

CRASH DATE                       0
CRASH TIME                       0
BOROUGH                          0
LATITUDE                         0
LONGITUDE                        0
NUMBER OF PERSONS INJURED        0
NUMBER OF PERSONS KILLED         0
NUMBER OF PEDESTRIANS INJURED    0
NUMBER OF PEDESTRIANS KILLED     0
NUMBER OF CYCLIST INJURED        0
NUMBER OF CYCLIST KILLED         0
NUMBER OF MOTORIST INJURED       0
NUMBER OF MOTORIST KILLED        0
dtype: int64

In [16]:
#Fixing the datatype
df["LATITUDE"] = df["LATITUDE"].astype("float64")
df["LONGITUDE"] = df["LONGITUDE"].astype("float64")

In [17]:
#Saving our cleaned data in a csv file
df.to_csv("./../../Dataset/cleaned_data.csv")